 import type { Router } from 'express'
import { supabaseAdmin } from '@vpn-enterprise/database'
import type { AuthRequest } from '@vpn-enterprise/auth'

export function registerGeneratedAppsRoutes(router: Router) {
  // List user's generated apps
  router.get('/apps/generated', async (req: AuthRequest, res) => {
    try {
      const userId = req.user?.id
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' })
      }

      const { data, error } = await (supabaseAdmin as any)
        .from('generated_apps')
        .select(`
          *,
          file_count:generated_app_files(count)
        `)
        .eq('user_id', userId)
        .order('created_at', { ascending: false })

      if (error) {
        return res
          .status(500)
          .json({ error: 'DB error', message: error.message })
      }

      res.json({ apps: data || [] })
    } catch (e: any) {
      res
        .status(500)
        .json({ error: 'Failed to list apps', message: e.message })
    }
  })

  // Get a specific generated app with files
  router.get('/apps/generated/:appId', async (req: AuthRequest, res) => {
    try {
      const userId = req.user?.id
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' })
      }

      const { appId } = req.params

      // Get app details
      const { data: app, error: appError } = await (supabaseAdmin as any)
        .from('generated_apps')
        .select('*')
        .eq('id', appId)
        .eq('user_id', userId)
        .single()

      if (appError || !app) {
        return res.status(404).json({ error: 'App not found' })
      }

      // Get app files
      const { data: files, error: filesError } = await (supabaseAdmin as any)
        .from('generated_app_files')
        .select('*')
        .eq('app_id', appId)
        .order('file_path', { ascending: true })

      if (filesError) {
        return res
          .status(500)
          .json({ error: 'Failed to load files', message: filesError.message })
      }

      res.json({
        app: {
          ...app,
          files: files || [],
        },
      })
    } catch (e: any) {
      res.status(500).json({ error: 'Failed to get app', message: e.message })
    }
  })

  // Save a newly generated app
  router.post('/apps/generated', async (req: AuthRequest, res) => {
    try {
      const userId = req.user?.id
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' })
      }

      const {
        app_name,
        description,
        framework,
        styling,
        features,
        dependencies,
        requires_database,
        files,
        tenant_id,
      } = req.body

      if (!app_name || !description || !framework || !files) {
        return res.status(400).json({
          error: 'Missing required fields: app_name, description, framework, files',
        })
      }

      // Insert app metadata
      const { data: app, error: appError } = await (supabaseAdmin as any)
        .from('generated_apps')
        .insert({
          user_id: userId,
          tenant_id: tenant_id || null,
          app_name,
          description,
          framework,
          styling: styling || null,
          features: features || [],
          dependencies: dependencies || {},
          requires_database: requires_database || false,
          status: 'generated',
        })
        .select()
        .single()

      if (appError) {
        return res
          .status(500)
          .json({ error: 'Failed to save app', message: appError.message })
      }

      // Insert app files
      const fileRecords = files.map((file: any) => ({
        app_id: app.id,
        file_path: file.path,
        content: file.content,
        language: file.language || 'text',
        file_size: file.content ? file.content.length : 0,
        is_entry_point: file.is_entry_point || false,
      }))

      const { error: filesError } = await (supabaseAdmin as any)
        .from('generated_app_files')
        .insert(fileRecords)

      if (filesError) {
        // Rollback app if files fail
        await (supabaseAdmin as any).from('generated_apps').delete().eq('id', app.id)
        return res
          .status(500)
          .json({ error: 'Failed to save files', message: filesError.message })
      }

      // Create first version
      await (supabaseAdmin as any)
        .from('generated_app_versions')
        .insert({
          app_id: app.id,
          version_number: 1,
          description: 'Initial generation',
          changes_summary: 'Generated by NexusAI',
          snapshot_data: {
            app,
            files: fileRecords,
          },
        })

      res.json({
        app: {
          ...app,
          files: fileRecords,
        },
        message: 'App saved successfully',
      })
    } catch (e: any) {
      res.status(500).json({ error: 'Failed to save app', message: e.message })
    }
  })

  // Update a generated app
  router.patch('/apps/generated/:appId', async (req: AuthRequest, res) => {
    try {
      const userId = req.user?.id
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' })
      }

      const { appId } = req.params
      const { app_name, description, status, deployment_url, files } = req.body

      // Verify ownership
      const { data: existing } = await (supabaseAdmin as any)
        .from('generated_apps')
        .select('id')
        .eq('id', appId)
        .eq('user_id', userId)
        .single()

      if (!existing) {
        return res.status(404).json({ error: 'App not found' })
      }

      // Update app metadata
      const updates: any = {}
      if (app_name !== undefined) updates.app_name = app_name
      if (description !== undefined) updates.description = description
      if (status !== undefined) updates.status = status
      if (deployment_url !== undefined) updates.deployment_url = deployment_url

      if (Object.keys(updates).length > 0) {
        const { error: updateError } = await (supabaseAdmin as any)
          .from('generated_apps')
          .update(updates)
          .eq('id', appId)

        if (updateError) {
          return res
            .status(500)
            .json({ error: 'Failed to update app', message: updateError.message })
        }
      }

      // Update files if provided
      if (files && Array.isArray(files)) {
        // Delete old files
        await (supabaseAdmin as any)
          .from('generated_app_files')
          .delete()
          .eq('app_id', appId)

        // Insert new files
        const fileRecords = files.map((file: any) => ({
          app_id: appId,
          file_path: file.path,
          content: file.content,
          language: file.language || 'text',
          file_size: file.content ? file.content.length : 0,
          is_entry_point: file.is_entry_point || false,
        }))

        await (supabaseAdmin as any)
          .from('generated_app_files')
          .insert(fileRecords)

        // Create new version
        const { data: versions } = await (supabaseAdmin as any)
          .from('generated_app_versions')
          .select('version_number')
          .eq('app_id', appId)
          .order('version_number', { ascending: false })
          .limit(1)

        const nextVersion = versions && versions[0] ? versions[0].version_number + 1 : 1

        await (supabaseAdmin as any)
          .from('generated_app_versions')
          .insert({
            app_id: appId,
            version_number: nextVersion,
            description: 'Updated by user',
            changes_summary: 'Files updated',
            snapshot_data: { files: fileRecords },
          })
      }

      res.json({ message: 'App updated successfully' })
    } catch (e: any) {
      res
        .status(500)
        .json({ error: 'Failed to update app', message: e.message })
    }
  })

  // Delete a generated app
  router.delete('/apps/generated/:appId', async (req: AuthRequest, res) => {
    try {
      const userId = req.user?.id
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' })
      }

      const { appId } = req.params

      // Verify ownership and delete
      const { error } = await (supabaseAdmin as any)
        .from('generated_apps')
        .delete()
        .eq('id', appId)
        .eq('user_id', userId)

      if (error) {
        return res
          .status(500)
          .json({ error: 'Failed to delete app', message: error.message })
      }

      res.json({ message: 'App deleted successfully' })
    } catch (e: any) {
      res
        .status(500)
        .json({ error: 'Failed to delete app', message: e.message })
    }
  })

  // Get app versions/history
  router.get('/apps/generated/:appId/versions', async (req: AuthRequest, res) => {
    try {
      const userId = req.user?.id
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' })
      }

      const { appId } = req.params

      // Verify ownership
      const { data: app } = await (supabaseAdmin as any)
        .from('generated_apps')
        .select('id')
        .eq('id', appId)
        .eq('user_id', userId)
        .single()

      if (!app) {
        return res.status(404).json({ error: 'App not found' })
      }

      // Get versions
      const { data: versions, error } = await (supabaseAdmin as any)
        .from('generated_app_versions')
        .select('*')
        .eq('app_id', appId)
        .order('version_number', { ascending: false })

      if (error) {
        return res
          .status(500)
          .json({ error: 'Failed to load versions', message: error.message })
      }

      res.json({ versions: versions || [] })
    } catch (e: any) {
      res
        .status(500)
        .json({ error: 'Failed to get versions', message: e.message })
    }
  })
}
